---
all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: '{{ proxmox_ip }}'
          ansible_user: '{{ proxmox_user }}'

    gitlab:
      hosts:
        git:
          ansible_host: '{{ gitlab_ip }}'
          ansible_user: '{{ gitlab_user }}'

    dev_vms:
      hosts:
        dev-vm-100:
          ansible_host: "{{ dev_vm_ip }}"
          ansible_user: "{{ gitlab_user}}"


